### ISSUE TITLE
Time zone field is getting cut

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#150]
The time zone field on the profile screen gets cut.
Device used: Micromax Canvas
![screenshot_2015-01-02-09-47-02](https://cloud.githubusercontent.com/assets/9797052/5594288/e4072c32-926a-11e4-8103-c5a00919795c.png)

**Comment by anujkhurana** [comment]
Please assign to amit not mobile team.

Let's only test on Samsung, Nexus 4 and iOS. We can ignore micromax cause
the app will be used in US where there is no micromax.

**Comment by anujkhurana** [comment]
@Deepak: I need a definitive answer on Samsung using android browser vs
chrome browser. From what I understand android 4.2 onwards android only
uses chrome browser.

If bug is related to the device using android browser instead of chrome
browser then the bug is invalid. We should only test with devices that use
chrome browser.
