### ISSUE TITLE
Save on measurement screen does not save the entered data

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#157]
Steps:
1.Go to profile screen ,enter data on the profile screen.
2.Click on save.

Current behaviour: If the user closes the app and reopens then Product list screen is displayed to the user however the data entered on 'save' is not displayed.
Expected behaviour: The data has to be saved on click of Save.

**Comment by NikhilAjency** [comment]
For measurements there are two entries for a particular user for two different dates. 
This implementation took care of History. But for fetching measurements data , currently it fetched all the records and not on the basis of date.
Fetching data based on the history has not been implemented and that's why it is fetching both the records...

**Comment by anujkhurana** [comment]
Please do not close this issue. I will like to understand why this is a
mobile task and not a task for Surekha.
