### ISSUE TITLE
Error message on save on measurements.

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#213]
Steps:
1. Hover on the mouse on the clickable area on the image on measurement screen.
2. When the field is displayed,Click on save.

Current Behaviour: An error message is given as shown in the screenshot
![measurement_new](https://cloud.githubusercontent.com/assets/9797052/5701631/02f8d4c2-9a74-11e4-9c9c-8f16fa31a34e.png)

**Comment by SurekhaRane** [comment]
There was a problem with tooltip.js.

Value entered doesn't get saved if tooltip is kept open. Also with the tooltip open, the hidden element for the particular text box is not found.

So the above error was reported with the tooltip open.

The mentioned issue has been fixed by keeping track of all the values entered by the user in an array and then passing the array to the server api.
