### ISSUE TITLE
Scrolling to select the number of  X2O bottles displays error on edit

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#310]
Steps:
1. Open edit product for X2O
2. Scroll on the slider to select the number of bottles

Current Behaviour:Text 'undefined' is displayed as in screenshot
![scroll_x2o](https://cloud.githubusercontent.com/assets/9797052/6035687/be14821a-ac5d-11e4-86fc-efca25056930.png)

**Comment by SurekhaRane** [comment]
This issue was reported while coding and was fixed before pushing it to the server.

The issue was reported because 

For any other supplements other than X2O , we have a drop down to select the number of servings.

In case of X2O , it is a slider which indicates the number of servings.

Basically in case of X2O it(dropdown) is hidden.

So whenever we change the slider, internally a value is set for the dropdown and that dropdown value is passed to the server.

But recently , it was said that number of servings can be greater than 3. This works perfectly for any other supplements.

But in case of X2O , it can be more than 3. So if the slider value was greater then 3 , dropdown used to not set the value and hence the issue was reported.

It is resolved by changing the logic.So now there is a separate field to keep track of number of servings.

**Comment by anujkhurana** [comment]
Nice update Surekha. Thanks.

**Comment by ashika123** [comment]
Fixed
