### ISSUE TITLE
Status messages are not displayed correctly on ios 7

### ISSUE THREAD

**Issue by ashika123** [ajency/xooma-track-go#395]
steps 
Open the home page(Date selected is today by  default)

Current behaviour: The messages for previous day are shown instead of for current date
Expected behaviour: The messages has to be displayed for the current date 
![img_1707](https://cloud.githubusercontent.com/assets/9797052/6322844/775ca83e-bb44-11e4-8825-769b9316ab8c.PNG)

**Comment by deepakpd** [comment]
The message "The day has passed by" is hardcoded text which is displayed when the selected date time does not match the current date time. This condition works for chrome but actual date time is "NaN" (i.e Not a number) on Safari browser due to which the mentioned issue occurs on iOS devices.

![image](https://cloud.githubusercontent.com/assets/6937147/6323454/64c52f8c-bb50-11e4-853f-2172e3f8cdba.png)

@SurekhaRane 
Issue in "homectrl.coffee"
Line: 499 and 837
parseInt(actual_time) is "NaN" on Safari.



￼

**Comment by ashika123** [comment]
Verified
